### ISSUE TITLE
NetworkTopologyRepresentation - NTR

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ApplicationRoadmap#40]
### Description
The NTR is for representing topology information that is stored in the #37 to humans.  
It could be agnostic to the kind of topology to be represented.  

### Dependencies
- [ ] With #37 the concepts and know-how for representation applications get defined.  
- [ ] The #5 is required for storing and providing the topology information that would be represented.  
- [ ] The #31 , #6 , #7 or #8 would be required for writing the topology information into the #5 .   
- [ ] For authentication purposes either the existing AdministratorAdministation (AA) application of the TinyApplicationController or a new #39 would be required.
